name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Generate PNG QR Code
        id: test-action-png
        uses: ./
        with:
          text: https://github.com/VeyronSakai/qr-code-generator
          output-path: test-qrcode.png
          type: png

      - name: Generate SVG QR Code
        id: test-action-svg
        uses: ./
        with:
          text: https://github.com/VeyronSakai/qr-code-generator
          output-path: test-qrcode.svg
          type: svg
          width: '512'
          margin: '2'

      - name: Verify QR Code Files
        id: verify
        shell: pwsh
        run: |
          # Check PNG file
          if (Test-Path "test-qrcode.png") {
            Write-Host "✅ PNG QR code file generated successfully"
            Get-Item "test-qrcode.png" | Format-List Name, Length, LastWriteTime
          } else {
            Write-Host "❌ PNG QR code file not found"
            exit 1
          }

          # Check SVG file
          if (Test-Path "test-qrcode.svg") {
            Write-Host "✅ SVG QR code file generated successfully"
            Get-Item "test-qrcode.svg" | Format-List Name, Length, LastWriteTime
          } else {
            Write-Host "❌ SVG QR code file not found"
            exit 1
          }

      - name: Upload QR Code Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qr-codes-${{ github.run_number }}
          path: |
            test-qrcode.png
            test-qrcode.svg
          retention-days: 7
